spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: validate
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml
  caching:
    eviction:
      cron:
        weather-conditions: 0 0 * * * *